###############################################################################
#                          Generated on dockerenv.io                          #
###############################################################################
version: "3.4"
services:
  cmts-demo-mysql:
    container_name: "cmts-demo-mysql"
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - cmts_demo_storage_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=comdata
      - MYSQL_USER=comuser
      - MYSQL_PASSWORD=compass
      - MYSQL_ROOT_HOST=%
    ports:
      - "1007:3306"

  comments-demo-php-fpm:
    container_name: "cd-php-fpm"
    build:
      context: .
    volumes:
      - ./app:/var/www/html

  comments-demo-nginx:
    container_name: "cd-nginx"
    image: nginx:alpine
    volumes:
      - ./dockerenv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
    ports:
     - "80:80"

volumes:
  cmts_demo_storage_mysql: